using System.Web.UI;
using Isis.Web.UI;

[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_arrow.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_cool.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_cry.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_e_biggrin.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_e_confused.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_e_geek.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_e_sad.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_e_smile.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_e_surprised.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_e_ugeek.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_e_wink.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_eek.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_evil.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_exclaim.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_idea.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_lol.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_mad.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_mrgreen.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_neutral.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_question.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_razz.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_redface.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_rolleyes.gif", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.Smilies.icon_twisted.gif", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.AddIns.Forums.Web.Resources.BBCodeEditor.js", "Zeus.AddIns.Forums.Web.Resources", "text/javascript")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.comment.png", "image/png")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.comment_edit.png", "image/png")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.comments.png", "image/png")]
[assembly: EmbeddedWebResource("Zeus.AddIns.Forums.Web.Resources.spacer.gif", "Zeus.AddIns.Forums.Web.Resources", "image/gif")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.user_comment.png", "image/png")]
[assembly: WebResource("Zeus.AddIns.Forums.Web.Resources.user_green.png", "image/png")]