using System.Web.UI;

[assembly: WebResource("Zeus.AddIns.ECommerce.Icons.arrow_branch.png", "image/png")]
[assembly: WebResource("Zeus.AddIns.ECommerce.Icons.arrow_divide.png", "image/png")]
[assembly: WebResource("Zeus.AddIns.ECommerce.Icons.arrow_join.png", "image/png")]
[assembly: WebResource("Zeus.AddIns.ECommerce.Icons.arrow_merge.png", "image/png")]
[assembly: WebResource("Zeus.AddIns.ECommerce.Icons.basket.png", "image/png")]
[assembly: WebResource("Zeus.AddIns.ECommerce.Icons.basket_go.png", "image/png")]
[assembly: WebResource("Zeus.AddIns.ECommerce.Icons.basket_put.png", "image/png")]
[assembly: WebResource("Zeus.AddIns.ECommerce.Icons.email_edit.png", "image/png")]
[assembly: WebResource("Zeus.AddIns.ECommerce.Icons.lorry.png", "image/png")]
[assembly: WebResource("Zeus.AddIns.ECommerce.Icons.lorry_go.png", "image/png")]
[assembly: WebResource("Zeus.AddIns.ECommerce.Icons.magnifier.png", "image/png")]
[assembly: WebResource("Zeus.AddIns.ECommerce.Icons.money.png", "image/png")]
[assembly: WebResource("Zeus.AddIns.ECommerce.Icons.money_pound.png", "image/png")]
[assembly: WebResource("Zeus.AddIns.ECommerce.Icons.package.png", "image/png")]
[assembly: WebResource("Zeus.AddIns.ECommerce.Icons.page_green.png", "image/png")]
[assembly: WebResource("Zeus.AddIns.ECommerce.Icons.page_red.png", "image/png")]
[assembly: WebResource("Zeus.AddIns.ECommerce.Icons.visa.png", "image/png")]