using System.Web.UI;
using Isis.Web.UI;

[assembly: WebResource("Zeus.Admin.Assets.MochaUI.Scripts.Source.Components.Tabs.js", "text/javascript")]
[assembly: WebResource("Zeus.Admin.Assets.MochaUI.Scripts.Source.Core.Core.js", "text/javascript")]
[assembly: WebResource("Zeus.Admin.Assets.MochaUI.Scripts.Source.Layout.Dock.js", "text/javascript")]
[assembly: WebResource("Zeus.Admin.Assets.MochaUI.Scripts.Source.Layout.Layout.js", "text/javascript")]
[assembly: WebResource("Zeus.Admin.Assets.MochaUI.Scripts.Source.Layout.Workspaces.js", "text/javascript")]
[assembly: WebResource("Zeus.Admin.Assets.MochaUI.Scripts.Source.Utilities.Themes.js", "text/javascript")]
[assembly: WebResource("Zeus.Admin.Assets.MochaUI.Scripts.Source.Window.Arrange-cascade.js", "text/javascript")]
[assembly: WebResource("Zeus.Admin.Assets.MochaUI.Scripts.Source.Window.Arrange-tile.js", "text/javascript")]
[assembly: WebResource("Zeus.Admin.Assets.MochaUI.Scripts.Source.Window.Modal.js", "text/javascript")]
[assembly: WebResource("Zeus.Admin.Assets.MochaUI.Scripts.Source.Window.Window.js", "text/javascript")]
[assembly: WebResource("Zeus.Admin.Assets.MochaUI.Scripts.Source.Windows-from-html.js", "text/javascript")]
[assembly: WebResource("Zeus.Admin.Assets.MochaUI.Scripts.Source.Windows-from-json.js", "text/javascript")]

[assembly: WebResource("Zeus.Admin.Assets.MochaUI.Scripts.excanvas_r43.js", "text/javascript")]
[assembly: WebResource("Zeus.Admin.Assets.MochaUI.Scripts.mootools-1.2-core.js", "text/javascript")]
[assembly: WebResource("Zeus.Admin.Assets.MochaUI.Scripts.mootools-1.2-more.js", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.css.Content.css", "Zeus.Admin.Assets", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.css.Core.css", "Zeus.Admin.Assets", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.css.Dock.css", "Zeus.Admin.Assets", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.css.Layout.css", "Zeus.Admin.Assets", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.css.Tabs.css", "Zeus.Admin.Assets", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.css.Window.css", "Zeus.Admin.Assets", "text/css")]

[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.images.arrow-right.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.images.bg-dropdown.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.images.bg-handle-horizontal.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.images.bg-header.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.images.bg-panel-header.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.images.collapse-expand.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.images.dock-tabs.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.images.handle-icon-horizontal.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.images.handle-icon.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.images.knob.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.images.logo-blank.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.images.logo.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.images.logo2.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.images.spacer2.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.images.spinner-placeholder.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.images.spinner.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.images.tabs.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.images.toolbox-divider.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.charcoal.images.toolbox-divider2.gif", "Zeus.Admin.Assets", "image/gif")]

[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.css.Content.css", "Zeus.Admin.Assets", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.css.Core.css", "Zeus.Admin.Assets", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.css.Dock.css", "Zeus.Admin.Assets", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.css.Layout.css", "Zeus.Admin.Assets", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.css.Tabs.css", "Zeus.Admin.Assets", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.css.Window.css", "Zeus.Admin.Assets", "text/css")]

[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.images.arrow-right.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.images.bg-dropdown.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.images.bg-handle-horizontal.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.images.bg-header.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.images.bg-panel-header.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.images.collapse-expand.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.images.dock-tabs.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.images.handle-icon-horizontal.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.images.handle-icon.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.images.knob.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.images.logo-blank.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.images.logo.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.images.logo2.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.images.spacer2.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.images.spinner-placeholder.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.images.spinner.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.images.tabs.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.images.toolbox-divider.gif", "Zeus.Admin.Assets", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Admin.Assets.MochaUI.Themes.default.images.toolbox-divider2.gif", "Zeus.Admin.Assets", "image/gif")]