//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeus.AddIns.ECommerce.Admin.Plugins.ManageOrders {
    
    
    public partial class Search {
        
        /// <summary>
        /// lsvOrders control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Zeus.Web.UI.WebControls.TypedListView lsvOrders;
        
        /// <summary>
        /// dpgSearchResultsPager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DataPager dpgSearchResultsPager;
        protected global::Zeus.Admin.Web.UI.WebControls.ToolbarButton btnBack;
        protected global::System.Web.UI.WebControls.Button btnSearch;

        protected global::System.Web.UI.WebControls.TextBox txtOrderNumber;
        protected global::System.Web.UI.WebControls.TextBox txtCustomerFirstName;
        protected global::System.Web.UI.WebControls.TextBox txtCustomerLastName;
        protected global::System.Web.UI.WebControls.TextBox txtCustomerEmail;
    }
}
