//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeus.Admin.FileManager {
    
    
    public partial class Default {
        
        /// <summary>
        /// ftrFileTree control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Zeus.Admin.Web.UI.WebControls.FileTree ftrFileTree;
    }
}
