//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bermedia.Gibbons.Web.UI.Views {
    
    
    public partial class CheckoutShippingAddress {
        
        /// <summary>
        /// rblDeliveryMethod control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtAddress1;
				protected global::System.Web.UI.WebControls.TextBox txtAddress2;
				protected global::System.Web.UI.WebControls.TextBox txtCity;
				protected global::System.Web.UI.WebControls.TextBox txtParishState;
				protected global::System.Web.UI.WebControls.TextBox txtZip;
				protected global::System.Web.UI.WebControls.DropDownList ddlCountry;
				protected global::System.Web.UI.WebControls.TextBox txtPhone;
        
        /// <summary>
        /// btnNext control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoundInTheory.DynamicImage.DynamicImageButton btnNext;
        
				protected global::System.Web.UI.WebControls.ListView lsvAddressBook;
    }
}
