using Isis.Web.UI;

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.langs.en.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.advhr.css.advhr.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.advhr.js.rule.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.advhr.langs.en_dlg.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.advhr.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.advhr.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.advhr.rule.htm", "Zeus.Web.Resources", "text/html")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.advimage.css.advimage.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.advimage.img.sample.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.advimage.js.image.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.advimage.langs.en_dlg.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.advimage.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.advimage.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.advimage.image.htm", "Zeus.Web.Resources", "text/html")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.advlink.css.advlink.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.advlink.js.advlink.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.advlink.langs.en_dlg.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.advlink.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.advlink.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.advlink.link.htm", "Zeus.Web.Resources", "text/html")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.autosave.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.autosave.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.bbcode.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.bbcode.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.compat2x.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.compat2x.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.contextmenu.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.contextmenu.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.directionality.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.directionality.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.dynamiccontent.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.dynamiccontent.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.dynamicimage.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.dynamicimage.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.emotions.img.smiley-cool.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.emotions.img.smiley-cry.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.emotions.img.smiley-embarassed.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.emotions.img.smiley-foot-in-mouth.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.emotions.img.smiley-frown.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.emotions.img.smiley-innocent.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.emotions.img.smiley-kiss.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.emotions.img.smiley-laughing.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.emotions.img.smiley-money-mouth.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.emotions.img.smiley-sealed.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.emotions.img.smiley-smile.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.emotions.img.smiley-surprised.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.emotions.img.smiley-tongue-out.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.emotions.img.smiley-undecided.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.emotions.img.smiley-wink.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.emotions.img.smiley-yell.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.emotions.js.emotions.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.emotions.langs.en_dlg.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.emotions.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.emotions.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.emotions.emotions.htm", "Zeus.Web.Resources", "text/html")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.example.img.example.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.example.js.dialog.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.example.langs.en.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.example.langs.en_dlg.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.example.dialog.htm", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.example.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.example.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.fullpage.css.fullpage.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.fullpage.js.fullpage.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.fullpage.langs.en_dlg.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.fullpage.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.fullpage.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.fullpage.fullpage.htm", "Zeus.Web.Resources", "text/html")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.fullscreen.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.fullscreen.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.fullscreen.fullscreen.htm", "Zeus.Web.Resources", "text/html")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.iespell.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.iespell.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.inlinepopups.skins.clearlooks2.img.alert.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.inlinepopups.skins.clearlooks2.img.button.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.inlinepopups.skins.clearlooks2.img.buttons.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.inlinepopups.skins.clearlooks2.img.confirm.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.inlinepopups.skins.clearlooks2.img.corners.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.inlinepopups.skins.clearlooks2.img.horizontal.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.inlinepopups.skins.clearlooks2.img.vertical.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.inlinepopups.skins.clearlooks2.window.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.inlinepopups.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.inlinepopups.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.inlinepopups.template.htm", "Zeus.Web.Resources", "text/html")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.insertdatetime.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.insertdatetime.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.layer.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.layer.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.media.css.content.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.media.css.media.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.media.img.flash.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.media.img.flv_player.swf", "Zeus.Web.Resources", "application/x-shockwave-flash")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.media.img.quicktime.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.media.img.realmedia.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.media.img.shockwave.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.media.img.trans.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.media.img.windowsmedia.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.media.js.embed.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.media.js.media.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.media.langs.en_dlg.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.media.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.media.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.media.media.htm", "Zeus.Web.Resources", "text/html")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.nonbreaking.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.nonbreaking.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.noneditable.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.noneditable.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.pagebreak.css.content.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.pagebreak.img.pagebreak.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.pagebreak.img.trans.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.pagebreak.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.pagebreak.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.paste.css.blank.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.paste.css.pasteword.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.paste.js.pastetext.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.paste.js.pasteword.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.paste.langs.en_dlg.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.paste.blank.htm", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.paste.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.paste.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.paste.pastetext.htm", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.paste.pasteword.htm", "Zeus.Web.Resources", "text/html")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.preview.jscripts.embed.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.preview.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.preview.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.preview.example.html", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.preview.preview.html", "Zeus.Web.Resources", "text/html")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.print.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.print.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.safari.blank.html", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.safari.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.safari.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.save.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.save.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.searchreplace.css.searchreplace.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.searchreplace.js.searchreplace.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.searchreplace.langs.en_dlg.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.searchreplace.advhr.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.searchreplace.advimage.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.searchreplace.advlink.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.searchreplace.advlink.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.searchreplace.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.searchreplace.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.searchreplace.en.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.searchreplace.en_dlg.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.searchreplace.image.htm", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.searchreplace.image.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.searchreplace.rule.htm", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.searchreplace.rule.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.searchreplace.img.sample.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.searchreplace.searchreplace.htm", "Zeus.Web.Resources", "text/html")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.spellchecker.css.content.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.spellchecker.img.wline.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.spellchecker.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.spellchecker.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.style.css.props.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.style.js.props.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.style.langs.en_dlg.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.style.advhr.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.style.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.style.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.style.en.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.style.en_dlg.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.style.props.htm", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.style.rule.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.tabfocus.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.tabfocus.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.table.css.cell.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.table.css.row.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.table.css.table.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.table.js.cell.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.table.js.merge_cells.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.table.js.row.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.table.js.table.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.table.langs.en_dlg.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.table.cell.htm", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.table.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.table.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.table.merge_cells.htm", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.table.row.htm", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.table.table.htm", "Zeus.Web.Resources", "text/html")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.template.css.template.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.template.js.template.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.template.langs.en_dlg.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.template.blank.htm", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.template.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.template.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.template.template.htm", "Zeus.Web.Resources", "text/html")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.visualchars.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.visualchars.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.xhtmlxtras.css.attributes.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.xhtmlxtras.css.popup.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.xhtmlxtras.js.abbr.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.xhtmlxtras.js.acronym.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.xhtmlxtras.js.attributes.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.xhtmlxtras.js.cite.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.xhtmlxtras.js.del.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.xhtmlxtras.js.element_common.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.xhtmlxtras.js.ins.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.xhtmlxtras.langs.en_dlg.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.xhtmlxtras.abbr.htm", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.xhtmlxtras.acronym.htm", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.xhtmlxtras.attributes.htm", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.xhtmlxtras.cite.htm", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.xhtmlxtras.del.htm", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.xhtmlxtras.editor_plugin.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.xhtmlxtras.editor_plugin_src.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.plugins.xhtmlxtras.ins.htm", "Zeus.Web.Resources", "text/html")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.img.colorpicker.jpg", "Zeus.Web.Resources", "image/jpeg")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.img.icons.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.js.about.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.js.anchor.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.js.charmap.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.js.color_picker.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.js.image.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.js.link.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.js.source_editor.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.langs.en.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.langs.en_dlg.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.skins.default.img.buttons.png", "Zeus.Web.Resources", "image/png")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.skins.default.img.items.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.skins.default.img.menu_arrow.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.skins.default.img.menu_check.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.skins.default.img.progress.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.skins.default.img.tabs.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.skins.default.content.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.skins.default.dialog.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.skins.default.ui.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.skins.o2k7.img.buttons_bg.png", "Zeus.Web.Resources", "image/png")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.skins.o2k7.img.buttons_bg_black.png", "Zeus.Web.Resources", "image/png")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.skins.o2k7.img.buttons_bg_silver.png", "Zeus.Web.Resources", "image/png")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.skins.o2k7.content.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.skins.o2k7.dialog.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.skins.o2k7.ui.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.skins.o2k7.ui_black.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.skins.o2k7.ui_silver.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.about.htm", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.anchor.htm", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.charmap.htm", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.color_picker.htm", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.editor_template.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.editor_template_src.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.image.htm", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.link.htm", "Zeus.Web.Resources", "text/html")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.advanced.source_editor.htm", "Zeus.Web.Resources", "text/html")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.simple.img.icons.gif", "Zeus.Web.Resources", "image/gif")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.simple.js.en.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.simple.skins.default.content.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.simple.skins.default.ui.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.simple.skins.o2k7.img.button_bg.png", "Zeus.Web.Resources", "image/png")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.simple.skins.o2k7.content.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.simple.skins.osk7.ui.css", "Zeus.Web.Resources", "text/css")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.simple.editor_template.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.themes.simple.editor_template_src.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.utils.editable_selects.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.utils.form_utils.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.utils.mctabs.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.utils.validate.js", "Zeus.Web.Resources", "text/javascript")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.tiny_mce.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.tiny_mce_popup.js", "Zeus.Web.Resources", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.TinyMCE.tiny_mce_src.js", "Zeus.Web.Resources", "text/javascript")]