using System.Web.UI;

[assembly: WebResource("Zeus.Admin.Assets.Images.Edit.FieldsetGradient.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Edit.inputGradient.png", "image/png")]

[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.arrow_up.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.bin.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.bin_closed.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.bin_empty.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.book_next.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.book_previous.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.bullet_arrow_bottom.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.bullet_arrow_down.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.bullet_key.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.cross.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.delete.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.disk.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.exclamation.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.information.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.LanguageMissing.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.page.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.page_add.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.page_copy.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.page_delete.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.page_save.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.page_white_code.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.tick.png", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Icons.zoom.png", "image/png")]

[assembly: WebResource("Zeus.Admin.Assets.Images.Login.button.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Login.mainBox.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Login.textBox.gif", "image/gif")]

[assembly: WebResource("Zeus.Admin.Assets.Images.Splitter.hgrabber.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Splitter.vdockbar.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Splitter.vgrabber.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Splitter.vgrabber2-active.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Splitter.vgrabber2-normal.gif", "image/gif")]

[assembly: WebResource("Zeus.Admin.Assets.Images.Theme.bannerBg.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Theme.logo.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Theme.logOut.gif", "image/gif")]

[assembly: WebResource("Zeus.Admin.Assets.Images.ThickBox.loadingAnimation.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.ThickBox.macFFBgHack.png", "image/png")]

[assembly: WebResource("Zeus.Admin.Assets.Images.Tree.arrow_refresh", "image/png")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Tree.collapsable-last.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Tree.collapsable.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Tree.expandable-last.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Tree.expandable.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Tree.leaf-last.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Tree.leaf.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Tree.line_bg.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Tree.line_bg_over.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Tree.line_bg_over_last.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Tree.spacer.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Tree.spinner.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.Tree.tree_line.gif", "image/gif")]

[assembly: WebResource("Zeus.Admin.Assets.Images.View.add.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.View.arrowDown.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.View.arrowSortable.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.View.arrowUp.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.View.button_arrow_left.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.View.button_arrow_right.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.View.cancel.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.View.confirm.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.View.edit.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.View.littleTick.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.View.trash.gif", "image/gif")]
[assembly: WebResource("Zeus.Admin.Assets.Images.View.trashOpen.gif", "image/gif")]

[assembly: WebResource("Zeus.Admin.Assets.Images.blank.gif", "image/gif")]