//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bermedia.Gibbons.Web.Plugins.Reports {
    
    
    public partial class SalesByTimeframe {
        
        /// <summary>
        /// uscDateRange control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bermedia.Gibbons.Web.Plugins.Reports.DateRange uscDateRange;
        
        /// <summary>
        /// lsvSales control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Isis.Web.UI.WebControls.TypedListView<Bermedia.Gibbons.Web.Plugins.Reports.SalesByTimeframe.SalesData> lsvSales;
    }
}
