using System;

namespace Protx.Vsp
{
	public enum VspParameter
	{
		_3DSecureStatus = 0x35,
		[Obsolete("use BillingAddress instead")] Address = 8,
		AddressResult = 0x36,
		AllowGiftAid = 0x2e,
		Amount = 4,
		Apply3DSecure = 0x30,
		ApplyAVSCV2 = 0x2f,
		AuthCode = 0x19,
		AVSCV2 = 20,
		Basket = 0x2a,
		BillingAddress = 0x22,
		BillingPostCode = 0x23,
		CardHolder = 0x17,
		CardNumber = 0x18,
		CardType = 30,
		CAVV = 50,
		ClientIPAddress = 0x31,
		ClientNumber = 0x16,
		ContactFax = 0x2c,
		ContactNumber = 0x2b,
		Crypt = 0x29,
		Currency = 5,
		CustomerEMail = 0x26,
		CustomerName = 0x21,
		CV2 = 0x1d,
		CV2Result = 0x38,
		DeliveryAddress = 0x24,
		DeliveryPostCode = 0x25,
		Description = 6,
		ECI = 0x34,
		eMailMessage = 40,
		ExpiryDate = 0x1b,
		FailureURL = 0x20,
		GiftAid = 0x39,
		GiftAidPayment = 0x2d,
		IssueNumber = 0x1c,
		NextURL = 12,
		NotificationURL = 7,
		[Obsolete("use BillingPostCode instead")] PostCode = 9,
		PostCodeResult = 0x37,
		RelatedSecurityKey = 0x12,
		RelatedTxAuthNo = 0x13,
		RelatedVendorTxCode = 0x11,
		RelatedVPSTxID = 0x10,
		SecurityKey = 14,
		StartDate = 0x1a,
		Status = 10,
		StatusDetail = 11,
		SuccessURL = 0x1f,
		TxAuthNo = 15,
		TxType = 1,
		Vendor = 2,
		VendorEMail = 0x27,
		VendorTxCode = 3,
		VPSProtocol = 0,
		VPSSignature = 0x15,
		VPSTxId = 13,
		XID = 0x33
	}
}