using System.Web.UI;

[assembly: WebResource("Zeus.Web.Resources.ColorPicker.blank.gif", "image/gif")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_background.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_hex.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_hsb_b.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_hsb_h.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_hsb_s.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_indic.gif", "image/gif")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_overlay.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_rgb_b.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_rgb_g.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_rgb_r.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_select.gif", "image/gif")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_submit.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_background.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_hex.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_hsb_b.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_hsb_h.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_hsb_s.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_indic.gif", "image/gif")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_rgb_b.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_rgb_g.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_rgb_r.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_submit.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.select.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.select2.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.slider.png", "image/png")]

[assembly: WebResource("Zeus.Web.Resources.jQuery.Plugins.jquery.colorpicker.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("Zeus.Web.Resources.jQuery.Plugins.jquery.colorpicker.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.Plugins.jquery.timePicker.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.Plugins.jquery.timePicker.css", "text/css")]

[assembly: WebResource("Zeus.Web.Resources.jQuery.jquery.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.TimePicker.css", "text/css")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.ui.core.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.ui.sortable.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.ui.tabs.js", "text/javascript")]

[assembly: WebResource("Zeus.Web.Resources.FancyFileUpload.attach.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.FancyFileUpload.bar.gif", "image/gif")]
[assembly: WebResource("Zeus.Web.Resources.FancyFileUpload.FancyFileUpload.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("Zeus.Web.Resources.FancyFileUpload.FancyUpload3.Attach2.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("Zeus.Web.Resources.FancyFileUpload.Fx.ProgressBar.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.FancyFileUpload.mootools.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.FancyFileUpload.progress.gif", "image/gif")]
[assembly: WebResource("Zeus.Web.Resources.FancyFileUpload.Swiff.Uploader.js", "text/javascript")]

[assembly: WebResource("Zeus.Web.Resources.miframe.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.tinymce.js", "text/javascript")]

[assembly: WebResource("Zeus.Web.Resources.xregexp-unicode-base.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.xregexp-unicode-categories.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.xregexp.js", "text/javascript")]