using System.Web.UI;
using Isis.Web.UI;

[assembly: WebResource("Zeus.Web.Resources.ColorPicker.blank.gif", "image/gif")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_background.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_hex.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_hsb_b.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_hsb_h.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_hsb_s.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_indic.gif", "image/gif")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_overlay.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_rgb_b.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_rgb_g.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_rgb_r.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_select.gif", "image/gif")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_submit.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_background.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_hex.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_hsb_b.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_hsb_h.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_hsb_s.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_indic.gif", "image/gif")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_rgb_b.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_rgb_g.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_rgb_r.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_submit.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.select.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.select2.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.slider.png", "image/png")]

[assembly: WebResource("Zeus.Web.Resources.Flags.gb.png", "image/png")]

[assembly: WebResource("Zeus.Web.Resources.Icons.bullet_key.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.Icons.bullet_world_link.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.Icons.folder.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.Icons.folder_key.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.Icons.group.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.Icons.group_key.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.Icons.page_white.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.Icons.page_white_acrobat.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.Icons.page_white_compressed.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.Icons.page_white_excel.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.Icons.page_white_picture.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.Icons.page_white_powerpoint.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.Icons.page_white_word.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.Icons.user.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.Icons.world.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.Icons.world_link.png", "image/png")]

[assembly: EmbeddedWebResource("Zeus.Web.Resources.jQuery.images.ui-bg_flat_0_aaaaaa_40x100.png", "Zeus.Web.Resources", "image/png")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.jQuery.images.ui-bg_flat_75_ffffff_40x100.png", "Zeus.Web.Resources", "image/png")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.jQuery.images.ui-bg_glass_55_fbf9ee_1x400.png", "Zeus.Web.Resources", "image/png")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.jQuery.images.ui-bg_glass_65_ffffff_1x400.png", "Zeus.Web.Resources", "image/png")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.jQuery.images.ui-bg_glass_75_dadada_1x400.png", "Zeus.Web.Resources", "image/png")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.jQuery.images.ui-bg_glass_75_e6e6e6_1x400.png", "Zeus.Web.Resources", "image/png")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.jQuery.images.ui-bg_glass_95_fef1ec_1x400.png", "Zeus.Web.Resources", "image/png")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.jQuery.images.ui-bg_highlight-soft_75_cccccc_1x100.png", "Zeus.Web.Resources", "image/png")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.jQuery.images.ui-icons_222222_256x240.png", "Zeus.Web.Resources", "image/png")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.jQuery.images.ui-icons_2e83ff_256x240.png", "Zeus.Web.Resources", "image/png")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.jQuery.images.ui-icons_454545_256x240.png", "Zeus.Web.Resources", "image/png")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.jQuery.images.ui-icons_888888_256x240.png", "Zeus.Web.Resources", "image/png")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.jQuery.images.ui-icons_cd0a0a_256x240.png", "Zeus.Web.Resources", "image/png")]

[assembly: WebResource("Zeus.Web.Resources.jQuery.Plugins.fg.menu.css", "text/css")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.Plugins.fg.menu.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.Plugins.jquery.colorpicker.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("Zeus.Web.Resources.jQuery.Plugins.jquery.colorpicker.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.Plugins.jquery.mcdropdown.css", "text/css")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.Plugins.jquery.mcdropdown.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.Plugins.jquery.timePicker.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.Plugins.jquery.timePicker.css", "text/css")]

[assembly: WebResource("Zeus.Web.Resources.jQuery.calendar.gif", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.DatePicker.css", "text/css")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.jquery.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.TimePicker.css", "text/css")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.ui.core.js", "text/javascript")]
[assembly: EmbeddedWebResource("Zeus.Web.Resources.jQuery.ui.css", "Zeus.Web.Resources", "text/css")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.ui.datepicker.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.ui.sortable.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.ui.tabs.js", "text/javascript")]

[assembly: WebResource("Zeus.Web.Resources.FileDataEditor.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.Silverlight.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.tinymce.js", "text/javascript")]