//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bermedia.Gibbons.Web.UI.UserControls
{


	public partial class ProductListing
	{
		protected global::Isis.Web.UI.WebControls.TypedListView<Bermedia.Gibbons.Web.Items.StandardProduct> lsvProducts;
	}
}
