//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bermedia.Gibbons.Web.UI.UserControls {
    
    
    public partial class ProductListing {
        
        /// <summary>
        /// h1Header control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl h1Header;

				protected global::System.Web.UI.WebControls.Label ltlPageLinks;
				protected global::System.Web.UI.WebControls.PlaceHolder plcPageLinks;
        
        /// <summary>
        /// lsvProducts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Isis.Web.UI.WebControls.TypedListView<Bermedia.Gibbons.Web.UI.UserControls.ProductGroup> lsvProducts;
    }
}
